version: "3.8"

services:
  bblvertx_elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: bblvertx_elastic
    environment:
      - node.name=elasticsearch
      - http.port=9200
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: always
    networks:
      - bblvertx
  bblvertx_postgres:
    image: postgres:9.4
    container_name: bblvertx_postgres
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=bblvertx
      - POSTGRES_USER=bblvertx
      - POSTGRES_DB=bblvertx
    networks:
      - bblvertx
    ports:
      - 5435:5432
  bblvertx_verticle:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: vertx_service
    container_name: bblvertx_verticle
    restart: always
    networks:
      - bblvertx
    ports:
      - 8071:80

networks:
  bblvertx:
    driver: bridge
